# 将项目构建镜像并推送至 Docker Hub
name: Build and push Docker image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # 存在子模块时需要添加以下参数
        # with:
        #   submodules: 'true'
        #   token: ${{ secrets.READONLY_TOKEN_FOR_GITHUB_ACTION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # Docker Hub 镜像仓库
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Docker Hub 镜像仓库
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-docker-template:${{ github.sha }} , ${{ secrets.DOCKER_HUB_USERNAME }}/python-docker-template:latest
